export const Club = {
  colors: {
    black: "#000000",
    primary: "#1E293B",
    surfacePanel: "#1E293B",
    surfacePage: "#F8FAFC",
    surfaceCard: "#FFFFFF",
    surfaceMuted: "#334155",
    textPrimary: "#1E293B",
    textSecondary: "#64748B",
    textTertiary: "#94A3B8",
    textOnDark: "#F8FAFC",
    textOnDarkMuted: "#94A3B8",
    actionInverted: "#F8FAFC",
    statusDanger: "#B42318",
    borderDefault: "#E2E8F0",
    borderOnDark: "rgba(248,250,252,0.35)",
    heroDim: "rgba(30,41,59,0.4)",
    scrim: ["transparent", "rgba(30,41,59,0.8)", "#1E293B"] as const,
  },
  space: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    gutter: 24,
  },
  radius: {
    badge: 4,
    field: 12,
    card: 12,
    panel: 24,
    pill: 999,
  },
  layout: {
    phoneMaxWidth: 430,
  },
  type: {
    // TODO(design): swap to Newsreader when ratified
    display: {
      fontFamily: "SourceSerif4_400Regular",
      fontSize: 34,
      lineHeight: 37,
      letterSpacing: -0.4,
    },
    headline: {
      fontFamily: "SourceSerif4_400Regular",
      fontSize: 28,
      lineHeight: 32,
      letterSpacing: -0.3,
    },
    title: {
      fontFamily: "SourceSerif4_400Regular",
      fontSize: 20,
      lineHeight: 24,
      letterSpacing: 0,
    },
    titleSm: {
      fontFamily: "SourceSerif4_400Regular",
      fontSize: 16,
      lineHeight: 20,
      letterSpacing: 0,
    },
    body: {
      fontFamily: "Inter_400Regular",
      fontSize: 17,
      lineHeight: 25,
    },
    bodySm: {
      fontFamily: "Inter_400Regular",
      fontSize: 15,
      lineHeight: 21,
    },
    caption: {
      fontFamily: "Inter_400Regular",
      fontSize: 13,
      lineHeight: 18,
    },
    button: {
      fontFamily: "Inter_500Medium",
      fontSize: 17,
      lineHeight: 17,
    },
    labelMono: {
      fontFamily: "JetBrainsMono_500Medium",
      fontSize: 11,
      lineHeight: 14,
      letterSpacing: 1.5,
    },
    factsMono: {
      fontFamily: "JetBrainsMono_400Regular",
      fontSize: 12,
      lineHeight: 17,
      letterSpacing: 1,
    },
    tabMono: {
      fontFamily: "JetBrainsMono_500Medium",
      fontSize: 9,
      lineHeight: 9,
      letterSpacing: 1,
    },
  },
} as const;
