/** Single import point for drizzle(). Each file is owned by exactly one module; the file name = the Postgres schema.
 *  auth.ts is generated by `npx @better-auth/cli generate` and edited once to use pgSchema("auth").
 *  platform schema lives in the platform module (relative import so drizzle-kit and runtime both resolve). */
export * from "../../../modules/platform/src/infrastructure/schema";
export * from "./members";
export * from "./notifications";
export * from "./proposals";
export * from "./engagement";
export * from "./crm";
export * from "./personalization";
export * from "./auth";
