/** Single import point for drizzle(). Each file is owned by exactly one module; the file name = the Postgres schema.
 *  auth.ts is generated by `npx @better-auth/cli generate` and edited once to use pgSchema("auth"). */
export * from "@bbc/platform/schema";   // the module owns its schema; packages/db only re-exports it
export * from "./members";
export * from "./notifications";
export * from "./proposals";
export * from "./engagement";
export * from "./crm";
export * from "./personalization";
export * from "./auth";
