/** Single import point for drizzle(). Each file is owned by exactly one module; the file name = the Postgres schema.
 *  auth.ts is generated by `npx @better-auth/cli generate` and edited once to use pgSchema("auth").
 *  platform schema lives in @bbc/platform (moved out of packages/db during unpack). */
export * from "@bbc/platform/schema";
export * from "./members";
export * from "./notifications";
export * from "./proposals";
export * from "./engagement";
export * from "./crm";
export * from "./personalization";
export * from "./auth";
