/** auth.* tables (pgSchema "auth"), generated by `npx @better-auth/cli generate`. The snapshot referenced this
 *  file but shipped the tables in packages/db; until identity owns them (same move as platform in 4.3), re-export. */
export * from "@bbc/db/schema/auth";
