/** Renders infra/cron/crontab. Format is what infra/cron/run.sh parses: five fields, then the job name ($6). */
export function renderCrontab(schedule: ReadonlyArray<{ name: string; cron: string }>): string {
  const head = [
    "# GENERATED by `bun run cron:gen` from the registered job specs (ADR-IMPL-021). Do not edit by hand.",
    "# HTTP jobs only — logic lives in the API (platform.jobs). Host jobs are in infra/host/crontab.",
  ];
  const width = [5, 3, 3, 3, 4] as const;
  const rows = schedule.map(({ name, cron }) => {
    const f = cron.split(" ");
    return f.map((x, i) => x.padEnd(width[i] ?? 1)).join("") + name;
  });
  return [...head, ...rows, ""].join("\n");
}
