/** Renders infra/cron/crontab. Format is what infra/cron/run.sh parses: five fields, then the job name ($6). */
export function renderCrontab(schedule: ReadonlyArray<{ name: string; cron: string }>): string {
  const head = [
    "# GENERATED by `bun run cron:gen` from the registered job specs (ADR-IMPL-021). Do not edit by hand.",
    "# HTTP jobs only — logic lives in the API (platform.jobs). Host jobs are in infra/host/crontab.",
  ];
  // Space-separated only — padEnd-then-join("") glues a long field (e.g. MON-FRI) to the next token
  // and run.sh loses $6 (the job name).
  const rows = schedule.map(({ name, cron }) => `${cron} ${name}`);
  return [...head, ...rows, ""].join("\n");
}
