/** The globe's land, decoded once per detail level. Data: Natural Earth via world-atlas (public domain), generated by
 *  packages/ui/scripts/globe-land.ts — never edit the JSON by hand. */
import type { Feature, FeatureCollection } from "geojson";
import { feature } from "topojson-client";
import type { GeometryCollection, Topology } from "topojson-specification";
import high from "./land/land-high.json";
import low from "./land/land-low.json";
import mid from "./land/land-mid.json";
import type { Detail } from "./globe-logic";

type Land = Topology<{ land: GeometryCollection }>;
const SOURCES: Record<Detail, Land> = {
  low: low as unknown as Land,
  mid: mid as unknown as Land,
  high: high as unknown as Land,
};
const decoded = new Map<Detail, Feature | FeatureCollection>();

export function landFor(detail: Detail): Feature | FeatureCollection {
  let geo = decoded.get(detail);
  if (!geo) {
    const topology = SOURCES[detail];
    geo = feature(topology, topology.objects.land);
    decoded.set(detail, geo);
  }
  return geo;
}
